### ISSUE TITLE
API Optimization Concerns

### ISSUE THREAD

**Issue by jakeyboi1** [VORPCORE/vorp_character-lua#104]
Hello Outsider how ya doin friend? Hope all is well! I could not open an issue on vorp_inventory repository... I wonder why? Huh guess we will never know. Anyway, about your "new" API I can see how you would think it is more optimal to call every export singularly as you may not use all of the API in your script. However making the call to vorp_inventory a separate resource every time I want to say check item count seems considerably less optimal than pulling it all at once. Just food for thought, would love to hear your opinion and reasoning, I look forward to your response!

**Comment by outsider31000** [comment]
vorp core was a fork and could only open an issue with the original repo, however that's no longer the case as we have separated the fork from the original for that particular reason a couple days ago (finally).

`However making the call to vorp_inventory a separate resource every time I want to say check item count`
So you think using the old method you not calling the resource everytime you need?

old API was using functions that would trigger events to set or get , same way as now, but events face some issues like race conditions etc there was too many steps just to get or set something.

`old api works this way` 
get all functions available, 1st call when resource starts (all resources call inventory on startup)
call function needed, 2 call (when you need to something done everytime will call a function from inventory)
trigger event that is inside the function called, 3rd call (after a function that has been called an event is triggered to set or get)

new api 
call export only once (direclty to the API to set or get)

I'm not sure I understand the meaning of this but If "you think" is better the old way,  you don't have to use the new, you can still use the old nothing was removed/changed. and it will remain unchanged and functional.

**Comment by outsider31000** [comment]
Some butt hurt response? 
Everything breaks for you and yet you want to lecture me how code works when can even figure it out simple things?  Please...
its none of your business what i do or dont do, what i know or dont know, go back to leak scripts thats what you do best. 
You Came here to try cause some drama you will be remove from the org.

**Comment by jakeyboi1** [comment]
Oops look like I hit a nerve, and hurt the ego. Silly me saying facts in the presence of all mighty Outsider, we all know that is a no no. Also on the topic of leaking paid scripts. Everyone in the community knows that is false, you are still spouting that nonsense? The code you claimed was stolen, was entirely different except I used 2 natives that, wait for it... are built into the game that you also happened to use. What really happened is I made free scripts that hurt your profit, and storefront because lets be honest vorp is just a store front. Also did syn not take I believe it was lrp_stables code base, add a couple things then sell it without permission? Before you begin throwing wild acvusations, maybe sweep under your own doorstep first. The hypocrisy in you is quite ridiculous. Good day.

**Comment by jakeyboi1** [comment]
Also you offered to teach someone how to break escrow on ymaps according to a very trusted friend of mine. Id advise you to clean your own closet out🤷‍♂️

**Comment by outsider31000** [comment]
you didnt leak any of my scripts how did that hurt my profit LEAKER

**Comment by outsider31000** [comment]
> Also you offered to teach someone how to break escrow on ymaps according to a very trusted friend of mine. Id advise you to clean your own closetsince when ymaps are escrowed xD

**Comment by outsider31000** [comment]
You are a leaker and every one knows it it's no secret.
buying paid scripts to release them for free then pretending to change variable names and move code around so they didnt look identic...

 you came here to harrass , to get a response, and I have put you in your place. 
 
 you werent the only one from your team to come here and harass
 someone else came here with some chat gpt bullshit too. yall seem to be very butt hurt somehow...

You have nothing better to do than coming here to harass others implying shit?
you want drama , you want a response, implying I break scripts for you, asking why new ways yare better than old cause somehow you think you know something I dont , well congratulation... I could not care less, you seem to have a problem with me which is very visible.

sort out your issues man and leave me alone.
