### ISSUE TITLE
Body and Waist bug

### ISSUE THREAD

**Issue by HowlRW** [VORPCORE/vorp_character-lua#105]
**Describe the issue**
When you create a new character your body type and waist isn't get saved!

**To Reproduce**
`. Enter on the server
2. Try to modify your body type!

**Expected behavior**
Video

**Screenshots**
https://youtu.be/g3oN1udKQRg

**Additional context**
No!

**Comment by outsider31000** [comment]
additional context 
did you update the script before testing? 
all files with no modifications

**Comment by HowlRW** [comment]
Fresh install!

**Comment by HowlRW** [comment]
Yes work perfect!!
