### ISSUE TITLE
The body and Legs Different colour Issue 

### ISSUE THREAD

**Issue by cocomonksky** [VORPCORE/vorp_character-lua#107]
when People create a black skin but their legs is getting white. after /rc

I try with different Black skin but still got the same result. after /rc it getting white on legs

this is the latest version of VORP character.

The Video of character creation 
https://cdn.discordapp.com/attachments/1013487110407331950/1214008672561397811/RedM_b1491_GTAProcess_2024.03.04-07.32.mp4?ex=65f78cae&is=65e517ae&hm=79433ff10e620191bbede5e5cc69e041fcc97869a89ea1023749beb05b9bcc2d&

After /rc

https://cdn.discordapp.com/attachments/1013487110407331950/1214008875573837844/RedM_b1491_GTAProcess_2024.03.04-07.34.mp4?ex=65f78cdf&is=65e517df&hm=c85083341901822603fcc5a245550755e12d2d2a41d2a46983a2af7488a32aa3&

**Comment by outsider31000** [comment]
says videos no longer available @cocomonksky
