### ISSUE TITLE
Clothing Tints Not Apply Correclty

### ISSUE THREAD

**Issue by Artzalez** [VORPCORE/vorp_character-lua#113]
**Describe the issue**
This error normally only happens in relation to the shirt and vest.

If you use dyes on a shirt and vest, you reconnect or use the RC command, the dyes are not applied, and it may be that another component causes them to be erased since sometimes you have time to see the colors in a microsecond but they disappear.

I have checked the data in the database and also checked the cache variables to see if the dyes had changed but they remain the same, the only thing is that they do not reappear until you go to a store and change to a previous number and return to the same dye number.

**To Reproduce**
Try my clothes in your DB and reconect:
[compPlayer](https://pastebin.com/st0pX89Z)
[compTints](https://pastebin.com/79c7p9CS)

**Screenshots**
What should clothes look like when connecting?
![image](https://github.com/VORPCORE/vorp_character-lua/assets/30190276/89563c6c-2bc2-45e1-b030-0ffa8179d767)

How it looks on connect
![image](https://github.com/VORPCORE/vorp_character-lua/assets/30190276/6e35a45b-aea4-4347-87d5-31365e21a842)

**Additional context**
[Video 1 (View how to fix shirt on store)](https://cdn.discordapp.com/attachments/1218184078227013683/1219315091464519790/2024-03-18_16-01-51.mp4?ex=660adaab&is=65f865ab&hm=1d77d475384d5c0f83a2bbc2f45cc35a2020afbe650602f95ed69cbfb76018ec&)

**Comment by Artzalez** [comment]
I found a temporally fix

**Comment by outsider31000** [comment]
Yeah  I see is the load order same we did with boots. I will look at it
