### ISSUE TITLE
HeadSize

### ISSUE THREAD

**Issue by highnoon12rp** [VORPCORE/vorp_character-lua#117]
Problem with not reading HeadSize from DB.

**Comment by highnoon12rp** [comment]
We've manage to fix this:

line 140 in client/client.lua
from:    if skin[v.comp] and skin[v.comp] > 0 then
to:   if skin[v.comp] and (skin[v.comp] >= -1 and skin[v.comp] <= 1) then

line 141 in client/client.lua
from:    SetCharExpression(ped, v.hash, skin[v.comp])
to:      SetCharExpression(ped, v.hash, skin[v.comp] * 1.0)

**Comment by reserect** [comment]
Use the templates supplied https://github.com/VORPCORE/vorp_character-lua/blob/main/pull_request_template.md

**Comment by reserect** [comment]
post a pull request here https://github.com/VORPCORE/vorp_character-lua/pulls

**Comment by outsider31000** [comment]
this should be fixed
