### ISSUE TITLE
character customization problem

### ISSUE THREAD

**Issue by Ellysiia** [VORPCORE/vorp_character-lua#118]
Hello,

I noticed that the creation of a character didn't work after disconnection.
I was creating my character, but as soon as I log out the face resets. 

I tried several options:
- Clean craches, logs, data (cache/game storage/nui-storage/server-cache/server-cache-priv)
- Wipe 7 times...
- Try different faces, skin colors, different customizations
- After creation, wait 30min before disconnecting or restart immediately
- Use 50 tokens for second chance
- Uninstall RedM

Despite everything, nothing changes. Neither wipe or second chance solves the problem

I'm sharing some images to illustrate this. 
Top: the character after creation, 
Bottom: his head after reco. 

I'm bringing this problem to your attention because several people have the same problem on the Last Country server...

Thanks a lot!
Elly

![perso1](https://github.com/VORPCORE/vorp_character-lua/assets/164402113/21742a47-607a-4a1a-88ad-25a3ab8dd7c6)
![perso2](https://github.com/VORPCORE/vorp_character-lua/assets/164402113/c3530b8e-980e-4e51-86f6-0250de117f72)

**Comment by Khorkovskiy** [comment]
Yes, it's true....It was a nightmare when we switched to this version and literally every third person said that his character had changed a lot and then we gave everyone a "second chance" so that they would return as it was...But there is one problem...Nothing was saved from the changes made by the players. By the way, there are 230-270 players online in prime time.

**Comment by outsider31000** [comment]
Have you install a new version? Not from release?
I put this on a server and they told me it was fixed.

**Comment by DeVerino-DVR** [comment]
I did the update yes but I think that for the new characters everything works I'm still looking

**Comment by Khorkovskiy** [comment]
> Have you install a new version? Not from release? I put this on a server and they told me it was fixed.

I updated it again yesterday. At least for the old characters, after the "second chance" it still resets. I can't say about the completely new characters.

**Comment by outsider31000** [comment]
this thread is not about second chance, is about the face settings

**Comment by outsider31000** [comment]
@Ellysiia  did you test with my changes?

**Comment by Ellysiia** [comment]
Hello @outsider31000

Yes indeed, I've tested it, and my face hasn't moved and remains as it was when I created it! :) 
I haven't tried it on a new character yet. But your changes solved the problem of the initial post 

Thanks a lot

**Comment by outsider31000** [comment]
thanks
