### ISSUE TITLE
Gender select help text not displaying

### ISSUE THREAD

**Issue by bganderson** [VORPCORE/vorp_character-lua#119]
**Describe the issue**
The very first time I loaded `vorp_character` from the `main` branch (**not** latest release) the help text at character gender selection (`Other.GenderChoice` / `_UI_FEED_POST_OBJECTIVE`) displayed correctly. After connecting again it didn't display again until I made a modification. 

**Using the latest release (1.6) it never displayed, not even on first run.** However, I didn't spend much time testing with the 1.6 release version.

On the `main` version, I changed `Wait(1000)` to `Wait(3000)` in `Setup()` in [client/createCharacter.lua](https://github.com/VORPCORE/vorp_character-lua/blob/main/client/createCharacter.lua#L61) and it now displays consistently. When I change the value back, it doesn't display.

**To Reproduce**
1. Load modules needed for `vorp_character`
2. Wait for character creation

**Expected behavior**
Consistently see the character gender select help text

**Additional context**
Ive only setup RedM for the first time this afternoon, so its very possible this is user error. My dev server is running an Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz so its possible my hardware has issues with this and production hardware wouldn't. If I have time, I'll load this on a faster box and see what happens. However, I feel like this would mostly be reliant on my client hardware, which is 11th gen i7. 

My server resources;
```
ensure oxmysql
ensure interiors
ensure weathersync
ensure vorp_menu
ensure vorp_core
ensure vorp_utils
ensure vorp_inputs
ensure vorp_character
```

My db schema is your pre-made [MariaDB.sql](https://github.com/VORPCORE/vorp_pre-made/blob/main/MariaDB.sql).

**Comment by outsider31000** [comment]
yeah this seems to happen depending on peoples location and hardware I did noticed that increasing the wait it welps, might need instead just show a quick notify and tell them what to press, but i havent seen anyone complaining about it since I first found this.

**Comment by outsider31000** [comment]
I havent seen anyone complaining about this issue so i guess its fixed?, feel free to open again.
