### ISSUE TITLE
Error: vorp_character was unable to execute a query!

### ISSUE THREAD

**Issue by FlipTastisch** [VORPCORE/vorp_character-lua#122]
i have a issu with Clothing Tints.

it say 
[script:oxmysql] Error: vorp_character was unable to execute a query!
[script:oxmysql] Query: INSERT INTO outfits (identifier, charidentifier, title, comps, compTints) VALUES (?, ?, ? ,?, ?)
[script:oxmysql] Unknown column 'compTints' in 'field list

and i can not save Outfits.

thanks ^^

**Comment by reserect** [comment]
Add the SQL https://discord.com/channels/704317931453939803/991855948345905182/1201158050535444520
