### ISSUE TITLE
Facefeatures lower then 0 will not appear

### ISSUE THREAD

**Issue by DaNeo61** [VORPCORE/vorp_character-lua#123]
FaceFeatures can be 0 and lower then zero and does not get applied to character when `and skin[v.comp] > 0`
With removing the part in the method it will appear correctly on character like it got set on editor.
```
local function LoadFaceFeatures(ped, skin)
	for key, value in pairs(Config.FaceFeatures) do
		for label, v in pairs(value) do
			if skin[v.comp] and skin[v.comp] > 0 then
				SetCharExpression(ped, v.hash, skin[v.comp])
			end
		end
	end
end
```
to
```
local function LoadFaceFeatures(ped, skin)
	for key, value in pairs(Config.FaceFeatures) do
		for label, v in pairs(value) do
			if skin[v.comp] then
				SetCharExpression(ped, v.hash, skin[v.comp])
			end
		end
	end
end
```

**Comment by outsider31000** [comment]
and then all the default features that have 0 gets applied and your character doesnt look the same. thats not  a fix. thats breaking other things

**Comment by outsider31000** [comment]
and your examples are old 
might want to update the script before opening an issue this issues has already been adressed
