### ISSUE TITLE
Overlay hair dan eyebrow its always gone after relogin...

### ISSUE THREAD

**Issue by cocomonksky** [VORPCORE/vorp_character-lua#126]
Hi... The Latest VORP Character makes The Overlay Hair dan The Eyebrows Gone After Relogin. Fresh Installed nothing changed

The Character From this 
https://media.discordapp.net/attachments/1013487110407331950/1254135373211369643/image.png?ex=66786415&is=66771295&hm=7a62002b2ea6789d15f653a8d8f6a9f33af9295e632ad0a9d4ce7ba36c478232&=&format=webp&quality=lossless&width=415&height=639

to These

https://media.discordapp.net/attachments/1013487110407331950/1254135292915482735/image.png?ex=66786402&is=66771282&hm=7e61db13aa1a7f7d2d0a71f983bb3821eb63a62f7a2190aca367d8f2b49479b3&=&format=webp&quality=lossless&width=657&height=639

**Comment by outsider31000** [comment]
Can you try the one from premade and see if the issues is fixed?

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_character-lua/assets/87246847/04448aff-814e-4145-805f-68206ea53c4d)
this is from an old character and the hair is there.

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_character-lua/assets/87246847/7e797da6-015e-4c33-bbe5-1710466122cd)
same thing with an old black character

I havent tested with new characters though.

**Comment by outsider31000** [comment]
@KadDarem  this issue seems happen because of your pull request if you can please have a look or ill have to revert it.
users say is when you create new characters
![image](https://github.com/VORPCORE/vorp_character-lua/assets/87246847/d5b44b35-d6e1-45a0-9954-d141bc85a68d)

**Comment by KadDarem** [comment]
Hi @outsider31000 

Can you send me the skin value from the DB ?

**Comment by outsider31000** [comment]
```{"grime_tx_id":1,"paintedmasks_palette_color_secondary":0,"lipsticks_tx_id":0,"ShouldersT":0.0,"paintedmasks_tx_id":0,"EyeLidL":0.0,"HeadType":1389122716,"paintedmasks_palette_color_primary":0,"foundation_palette_color_primary":0,"MouthCLLD":0.0,"Torso":2966572863,"paintedmasks_visibility":0,"paintedmasks_opacity":0,"FaceD":0.0,"MouthX":0.0,"BodyType":3447687317,"shadows_palette_color_tertiary":0,"MouthCRW":0.0,"LegsS":0.0,"MouthCRLD":0.0,"NoseC":0.0,"eyeliner_tx_id":0,"CalvesS":0.0,"foundation_palette_color_tertiary":0,"spots_visibility":1,"disc_visibility":0,"ChestS":0.0,"beardstabble_tx_id":1,"eyebrows_opacity":1.0,"freckles_tx_id":0,"scars_visibility":1,"Eyes":612262189,"paintedmasks_palette_color_tertiary":0,"disc_opacity":0,"EyeLidH":0.0,"lipsticks_palette_id":0,"Body":-20262001,"FaceS":0.0,"blush_tx_id":0,"ChinW":0.0,"lipsticks_palette_color_primary":0,"EyeDis":0.0,"spots_opacity":1.0,"blush_opacity":0,"MouthCRD":0.0,"blush_palette_color_primary":0,"NeckD":0.0,"EyeBrowW":0.0,"EarsW":0.0,"foundation_palette_id":0,"LegsType":1389117221,"sex":"mp_male","NoseH":0.0,"ArmsS":0.0,"moles_visibility":0,"MouthCRH":0.0,"EyeH":0.0,"MouthD":0.0,"EyeAng":0.0,"complex_tx_id":0,"ShouldersS":0.0,"NoseDis":0.0,"eyebrows_color":1064202495,"ageing_visibility":1,"EyeLidR":0.0,"Beard":1257638385,"LLiphD":0.0,"EarsH":0.0,"eyebrows_tx_id":22,"foundation_palette_color_secondary":0,"LLiphH":0.0,"FaceW":0.0,"HipsS":0.0,"scars_opacity":1.0,"EarsA":0.0,"paintedmasks_palette_id":0,"JawD":0.0,"EyeBrowD":0.0,"ULiphD":0.0,"eyeliner_visibility":0,"CheekBonesH":0.0,"complex_visibility":0,"HeadSize":0.0,"Legs":1207869376,"JawH":0.0,"ULiphW":0.0,"foundation_opacity":0,"MouthCLH":0.0,"foundation_tx_id":0,"freckles_visibility":0,"moles_opacity":0,"hair_opacity":0,"eyeliner_color_primary":0,"foundation_visibility":0,"beardstabble_visibility":1,"Hair":2003861717,"ChinD":0.0,"hair_color_primary":0,"ageing_opacity":1.0,"hair_visibility":1,"NoseS":0.0,"ShouldersM":0.0,"Waist":1960266524,"blush_palette_id":0,"blush_visibility":0,"eyeliner_palette_id":0,"shadows_opacity":0,"eyeliner_opacity":0,"shadows_palette_id":0,"lipsticks_opacity":0,"beardstabble_color_primary":17129595,"spots_tx_id":7,"MouthY":0.0,"shadows_palette_color_primary":0,"MouthCLD":0.0,"lipsticks_palette_color_tertiary":0,"shadows_tx_id":0,"shadows_visibility":0,"beardstabble_opacity":1.0,"shadows_palette_color_secondary":0,"lipsticks_visibility":0,"NeckW":0.0,"CheekBonesW":0.0,"grime_opacity":1.0,"MouthW":0.0,"NoseAng":0.0,"moles_tx_id":0,"scars_tx_id":14,"CheekBonesD":0.0,"EyeD":0.0,"EyeBrowH":0.0,"freckles_opacity":0,"MouthCLW":0.0,"ageing_tx_id":20,"WaistW":0.0,"acne_opacity":0,"acne_tx_id":0,"grime_visibility":1,"complex_opacity":0,"disc_tx_id":0,"lipsticks_palette_color_secondary":0,"eyebrows_visibility":1,"Scale":1.05,"ChinH":0.0,"JawW":0.0,"LLiphW":0.0,"ULiphH":0.0,"acne_visibility":0,"hair_tx_id":0,"NoseW":0.0,"EarsD":0.0,"EyeLidW":0.0}```

```{"blush_visibility":0,"HipsS":0.0,"MouthCRLD":0.0,"eyeliner_opacity":0,"MouthCLLD":0.0,"paintedmasks_palette_color_tertiary":0,"NeckD":0.0,"LLiphH":0.0,"FaceS":0.0,"scars_tx_id":0,"hair_tx_id":0,"MouthW":0.0,"NoseW":0.0,"JawH":0.0,"NoseDis":0.0,"EarsA":0.0,"acne_opacity":0,"EyeD":0.0,"grime_opacity":0,"ULiphH":0.0,"EyeDis":0.0,"CheekBonesD":0.0,"MouthCLH":0.0,"foundation_palette_color_secondary":0,"eyeliner_palette_id":0,"foundation_tx_id":0,"ChinD":0.0,"spots_opacity":0,"ageing_visibility":0,"paintedmasks_palette_color_secondary":0,"ShouldersT":0.0,"lipsticks_palette_color_tertiary":0,"NoseH":0.0,"disc_tx_id":0,"MouthCRW":0.0,"disc_visibility":0,"moles_opacity":0,"JawD":0.0,"ULiphW":0.0,"acne_tx_id":0,"freckles_tx_id":0,"Legs":174153218,"scars_opacity":0,"LLiphW":0.0,"EyeLidH":0.0,"Scale":1.0,"grime_visibility":0,"WaistW":0.0,"paintedmasks_tx_id":0,"blush_palette_id":0,"shadows_visibility":0,"overlays":{"eyebrow":{"id":7,"opacity":1.0},"freckles":{"id":3,"opacity":1.0},"scar":{"id":1,"opacity":1.0},"beard":{"tint0":3153346296,"opacity":1.0,"id":1}},"blush_palette_color_primary":0,"ChinW":0.0,"CalvesS":0.0,"beardstabble_visibility":0,"Waist":-325933489,"NeckW":0.0,"FaceD":0.0,"freckles_opacity":0,"NoseAng":0.0,"eyebrows_tx_id":0,"foundation_palette_id":0,"NoseS":0.0,"scars_visibility":0,"foundation_palette_color_tertiary":0,"MouthCLD":0.0,"shadows_palette_id":0,"MouthCRH":0.0,"Hair":-277107907,"MouthY":0.0,"eyebrows_color":0,"eyebrows_visibility":0,"EyeH":0.0,"ChestS":0.0,"eyeliner_color_primary":0,"shadows_palette_color_primary":0,"acne_visibility":0,"MouthX":0.0,"foundation_visibility":0,"moles_visibility":0,"paintedmasks_visibility":0,"EyeLidR":0.0,"eyebrows_opacity":0.0,"lipsticks_visibility":0,"Body":-369348190,"spots_tx_id":0,"ULiphD":0.0,"hair_opacity":0,"EyeAng":0.0,"moles_tx_id":0,"paintedmasks_palette_id":0,"JawW":0.0,"ageing_tx_id":0,"Beard":-922168742,"hair_color_primary":0,"CheekBonesH":0.0,"NoseC":0.0,"foundation_opacity":0,"EarsH":0.0,"Eyes":2501331517,"grime_tx_id":0,"lipsticks_opacity":0,"EyeBrowW":0.0,"HeadSize":0.0,"blush_opacity":0,"beardstabble_opacity":0,"complex_opacity":0,"MouthCLW":0.0,"complex_visibility":0,"EarsW":0.0,"EyeBrowH":0.0,"CheekBonesW":0.0,"shadows_palette_color_secondary":0,"EarsD":0.0,"beardstabble_color_primary":0,"paintedmasks_opacity":0,"ageing_opacity":0,"shadows_palette_color_tertiary":0,"EyeBrowD":0.0,"spots_visibility":0,"lipsticks_palette_color_primary":0,"Torso":62321923,"FaceW":0.0,"MouthCRD":0.0,"MouthD":0.0,"freckles_visibility":0,"hair_visibility":0,"complex_tx_id":0,"eyeliner_tx_id":0,"shadows_opacity":0,"paintedmasks_palette_color_primary":0,"blush_tx_id":0,"lipsticks_tx_id":0,"ChinH":0.0,"EarsL":0.0,"lipsticks_palette_id":0,"LegsType":2289847408,"LegsS":0.0,"lipsticks_palette_color_secondary":0,"EyeLidL":0.0,"LLiphD":0.0,"EyeLidW":0.0,"eyeliner_visibility":0,"ArmsS":0.0,"shadows_tx_id":0,"beardstabble_tx_id":0,"sex":"mp_male","albedo":1557597939,"foundation_palette_color_primary":0,"disc_opacity":0,"HeadType":1108478392,"ShouldersS":0.0,"ShouldersM":0.0,"BodyType":1807137864}```

```{"lipsticks_tx_id":0,"ULiphH":0.0,"ULiphD":0.0,"NoseW":0.0,"grime_opacity":0,"MouthY":0.0,"foundation_palette_color_primary":0,"LLiphD":0.0,"EyeLidH":0.0,"MouthW":1.0,"FaceD":0.0,"JawH":0,"freckles_tx_id":0,"lipsticks_opacity":0,"NoseDis":0.0,"EyeAng":0.0,"foundation_palette_color_tertiary":0,"MouthX":0.0,"NoseS":0.0,"Body":-369348190,"EarsH":0.0,"eyebrows_opacity":1.0,"eyeliner_color_primary":0,"NoseH":0.0,"EyeBrowH":0.0,"CheekBonesH":0,"lipsticks_visibility":0,"WaistW":-1.0,"shadows_palette_color_primary":0,"ShouldersS":0.2,"MouthCRH":0.0,"foundation_tx_id":0,"paintedmasks_visibility":0,"LegsS":1.0,"EarsA":0.0,"ShouldersM":0.3,"eyebrows_tx_id":4,"blush_tx_id":0,"EarsW":0.0,"JawW":1.0,"grime_visibility":0,"EyeLidW":0.0,"spots_visibility":0,"Hair":3597829160,"sex":"mp_male","shadows_visibility":0,"MouthCLD":0,"MouthD":0.0,"beardstabble_tx_id":1,"ChinW":0.0,"shadows_palette_color_tertiary":0,"shadows_opacity":0,"MouthCLH":0,"MouthCRD":0.0,"beardstabble_color_primary":1734720533,"eyeliner_visibility":0,"lipsticks_palette_id":0,"EyeD":0.0,"MouthCLW":0.2,"MouthCRLD":0.0,"BodyType":1210379577,"eyebrows_color":1734720533,"blush_palette_id":0,"EyeLidR":0.0,"lipsticks_palette_color_tertiary":0,"Waist":-2045421226,"eyeliner_opacity":0,"spots_opacity":0,"CheekBonesW":-0.5,"eyeliner_tx_id":0,"ChestS":1.0,"eyebrows_visibility":1,"paintedmasks_palette_color_secondary":0,"disc_visibility":0,"ChinD":0.0,"acne_visibility":0,"ArmsS":1.0,"FaceS":0.0,"ShouldersT":0.4,"eyeliner_palette_id":0,"foundation_visibility":0,"ageing_opacity":0.3,"MouthCRW":0.0,"freckles_opacity":0,"foundation_opacity":0,"Legs":2968922921,"paintedmasks_opacity":0,"hair_opacity":1.0,"HipsS":-0.1,"paintedmasks_palette_color_primary":0,"ageing_visibility":1,"paintedmasks_palette_id":0,"ageing_tx_id":25,"LLiphW":0.0,"scars_opacity":1.0,"disc_opacity":0,"foundation_palette_color_secondary":0,"HeadType":549367063,"shadows_tx_id":0,"foundation_palette_id":0,"NeckW":0.0,"EarsD":0.0,"paintedmasks_palette_color_tertiary":0,"CheekBonesD":0.0,"spots_tx_id":0,"hair_visibility":1,"EyeH":0.0,"blush_opacity":0,"blush_palette_color_primary":0,"blush_visibility":0,"beardstabble_opacity":1.0,"beardstabble_visibility":1,"shadows_palette_color_secondary":0,"shadows_palette_id":0,"lipsticks_palette_color_secondary":0,"FaceW":0.0,"ULiphW":0.0,"lipsticks_palette_color_primary":0,"grime_tx_id":0,"moles_opacity":0,"NoseC":0.0,"MouthCLLD":0.0,"moles_tx_id":0,"EyeBrowW":0.0,"EyeBrowD":0.0,"moles_visibility":0,"complex_opacity":0,"paintedmasks_tx_id":0,"CalvesS":1.0,"acne_opacity":0,"acne_tx_id":0,"freckles_visibility":0,"Scale":1.05,"complex_visibility":0,"disc_tx_id":0,"hair_color_primary":1734720533,"EyeDis":0.0,"HeadSize":0.0,"scars_visibility":1,"complex_tx_id":0,"Eyes":2501331517,"Beard":-1,"LegsType":3723790941,"JawD":0,"NoseAng":0.0,"LLiphH":0.0,"hair_tx_id":1,"scars_tx_id":2,"EyeLidL":0.0,"Torso":1180660122,"ChinH":0.0,"NeckD":0.0}```

someone sent me this.
@KadDarem

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_character-lua/assets/87246847/1d3f2af6-f871-415b-b092-dc480ea2bf9d)
![image](https://github.com/VORPCORE/vorp_character-lua/assets/87246847/33a2f120-0eda-49e1-a66d-9eb959180d40)

it was confirmed without your pr this doesn't happen.

**Comment by RealStonerGamer** [comment]
https://github.com/VORPCORE/vorp_character-lua/issues/126#issuecomment-2191338030
> Hi @outsider31000
> 
> Can you send me the skin value from the DB ?

here is another one as well that did the same thing changed skin of face from white to black after this PR so here is the data from another character doing it 



<details><summary>compTints</summary>
<p>

```lua
{"Belt":{"-634319003":{"index":8,"color":2,"palette":0,"tint2":0,"tint1":0,"tint0":0}},"Vest":{"-1801698361":{"palette":1064202495,"tint2":8,"tint1":26,"tint0":23}}}

``` 


</p>
</details> 



<details><summary>CompPlayer</summary>
<p>


```lua
{"Gauntlets":-1,"NeckTies":-1,"Coat":-1,"RingRh":-1,"Loadouts":-1,"Spurs":-1,"bow":-1,"Vest":3576878867,"Buckle":-1,"teeth":-1,"armor":-1,"Suspender":-1,"Spats":-1,"Poncho":-1,"Dress":-1,"Mask":-1,"Badge":-1,"Bracelet":-1,"Accessories":-1,"Gunbelt":-1,"Glove":-1,"Cloak":-1,"Satchels":-1,"Pant":2147953136,"RingLh":-1,"Shirt":2185468631,"Chap":-1,"Teeth":-1,"Holster":-1,"GunbeltAccs":-1,"Belt":-1,"Armor":-1,"EyeWear":-1,"Skirt":-1,"Hat":3668674537,"NeckWear":-1,"CoatClosed":-1,"Boots":3244573491}

``` 



</p>
</details> 




<details><summary>skinPlayer </summary>
<p>


```lua
{"hair_visibility":0,"JawH":0.0,"EyeLidR":0.0,"FaceD":0.0,"ChestS":0.0,"foundation_palette_color_tertiary":0,"ShouldersS":0.0,"eyeliner_opacity":0,"Body":4274705295,"Beard":-1,"EyeLidW":0.0,"Scale":0.0,"lipsticks_visibility":0,"EarsH":0.0,"LegsS":0.0,"beardstabble_opacity":0,"complex_opacity":0,"JawW":0.0,"HipsS":0.0,"ShouldersM":0.0,"hair_tx_id":0,"foundation_visibility":0,"LLiphW":0.0,"NoseS":0.0,"LegsType":-2068143351,"ULiphW":0.0,"MouthCRLD":0.0,"eyeliner_color_primary":0,"WaistW":0.0,"foundation_palette_color_primary":0,"Waist":3021518216,"EarsD":0.0,"EyeBrowD":0.0,"hair_color_primary":0,"CheekBonesH":0.0,"beardstabble_tx_id":0,"paintedmasks_palette_color_primary":0,"paintedmasks_palette_color_secondary":0,"MouthCLH":0.0,"ChinW":0.0,"eyeliner_tx_id":0,"HeadSize":0.0,"Torso":543187419,"JawD":0.0,"acne_opacity":0,"ageing_tx_id":0,"freckles_visibility":0,"blush_opacity":0,"lipsticks_palette_color_primary":0,"blush_palette_color_primary":0,"EyeH":0.0,"paintedmasks_palette_id":0,"HeadType":1218683388,"scars_opacity":0,"sex":"mp_male","spots_visibility":0,"grime_opacity":0,"eyebrows_opacity":0.0,"EarsA":0.0,"paintedmasks_tx_id":0,"albedo":317354806,"scars_tx_id":8,"ShouldersT":0.0,"freckles_tx_id":0,"NeckW":0.0,"disc_opacity":0,"lipsticks_palette_id":0,"EarsL":0.0,"LLiphD":0.0,"moles_visibility":0,"NoseC":0.0,"eyebrows_tx_id":11,"scars_visibility":1,"lipsticks_palette_color_tertiary":0,"moles_tx_id":0,"ULiphD":0.0,"EyeAng":0.0,"blush_palette_id":0,"disc_tx_id":0,"eyeliner_palette_id":0,"Hair":2471030136,"EyeLidL":0.0,"foundation_opacity":0,"MouthY":0.0,"shadows_visibility":0,"CalvesS":0.0,"shadows_palette_color_tertiary":0,"grime_tx_id":0,"EarsW":0.0,"eyebrows_visibility":1,"shadows_opacity":0,"hair_opacity":0,"grime_visibility":0,"MouthX":0.0,"shadows_palette_color_primary":0,"MouthD":0.0,"EyeD":0.0,"paintedmasks_palette_color_tertiary":0,"complex_visibility":0,"EyeBrowW":0.0,"MouthW":0.0,"blush_visibility":0,"CheekBonesW":0.0,"disc_visibility":0,"EyeLidH":0.0,"NoseH":0.0,"lipsticks_tx_id":0,"CheekBonesD":0.0,"spots_opacity":0,"MouthCLD":0.0,"lipsticks_palette_color_secondary":0,"BodyType":1257168263,"MouthCLW":0.0,"FaceW":0.0,"blush_tx_id":0,"eyebrows_color":0,"EyeDis":0.0,"EyeBrowH":0.0,"beardstabble_color_primary":0,"acne_tx_id":0,"ChinD":0.0,"shadows_palette_id":0,"paintedmasks_opacity":0,"ArmsS":0.0,"NoseDis":0.0,"acne_visibility":0,"LLiphH":0.0,"paintedmasks_visibility":0,"MouthCRH":0.0,"moles_opacity":0,"MouthCRD":0.0,"FaceS":0.0,"beardstabble_visibility":0,"ULiphH":0.0,"freckles_opacity":0,"MouthCRW":0.0,"foundation_palette_color_secondary":0,"eyeliner_visibility":0,"shadows_tx_id":0,"NeckD":0.0,"complex_tx_id":0,"ageing_opacity":0,"NoseAng":0.0,"ageing_visibility":1,"ChinH":0.0,"shadows_palette_color_secondary":0,"lipsticks_opacity":0,"MouthCLLD":0.0,"spots_tx_id":0,"NoseW":0.0,"foundation_tx_id":0,"foundation_palette_id":0,"Eyes":46507404} 
``` 


</p>
</details>

**Comment by KadDarem** [comment]
> 1389122716

I will check. The hash of body components are wrong. Head components has not the same than tone than body component. 
Example with your values @RealStonerGamer : The head is 1218683388 = CLOTHING_ITEM_M_HEAD_009_V_006 = tone number 6 and the body is 543187419 = CLOTHING_ITEM_M_BODIES_UPPER_000_V_001 = tone number 1. 
Before my PR, the hashes are wrong too, but due to the head texture was replaced by a default value, the issue was hidden by that.

**Comment by KadDarem** [comment]
Because the script replaced the head texture by the "right" tone color. So your head component was black too but the script overwrited the skin color with the white color. But this process also removed the material and normal texture of the head. So your head texture had less detail and every head of the same tone used the same texutre. 

It's not the case with the new way to apply head component. I don't overwrite the head tone because it's already the right tone. So the default texture of the component is keeped and also the material and normal texture = better design of the head.

Is it more understandable ?

**Comment by RealStonerGamer** [comment]
> Because the script replaced the head texture by the "right" tone color. So your head component was black too but the script overwrited the skin color with the white color. But this process also removed the material and normal texture of the head. So your head texture had less detail and every head of the same tone used the same texutre.
> 
> It's not the case with the new way to apply head component. I don't overwrite the head tone because it's already the right tone. So the default texture of the component is keeped and also the material and normal texture = better design of the head.
> 
> Is it more understandable ?

Unfortunately, this still does not address the main issue players are facing with character changes. Players designed their characters to look a specific way, but your PR has "fixed" the textures, causing confusion. I am unsure why these textures turned black in the first place, as they were originally white. Now, some players' characters appear white when they should be black. This affects hundreds of players on my server and thousands across all servers using this character system. Are you suggesting that all these players need to remake their characters and won't be able to use the faces or skins they had before?

This will cause a huge issue in the VORP community, as hundreds of servers use this script and will face problems with their old characters. I've also seen a few new characters report similar issues. Are you sure there is nothing wrong?

**Comment by KadDarem** [comment]
It should be possible to fix the wrong head component by replace the hash if it's not the same tone than the torso. 

For new characters, I will try to create a new one to test. Do you know the heritage setting to choose to have the issue ? (skin tone, head number).

**Comment by outsider31000** [comment]
> It should be possible to fix the wrong head component by replace the hash if it's not the same tone than the torso

Note that in the images I shared  it's not only the head that is wrong.


@DerHobbs  @RealStonerGamer  can we get a video in how this is achieved ?

**Comment by KadDarem** [comment]
> > It should be possible to fix the wrong head component by replace the hash if it's not the same tone than the torso
> 
> Note that in the images I shared  it's not only the head that is wrong.
> 
> 
> @DerHobbs @cocomonksky    @RealStonerGamer  can we get a video in how this is achieved ? 
> 
> 

I didn't edit the other body parts, only the head component. I don't think these one are from my PR.

**Comment by RealStonerGamer** [comment]
> Note that in the images I shared it's not only the head that is wrong.

for me it was just the head that was reported and that changed  
all we did was update the character script and then some heads color changed  to black from white 

> @DerHobbs @cocomonksky @RealStonerGamer can we get a video in how this is achieved ?

there is not really anything i can make a video on to recreate the issue 

> It should be possible to fix the wrong head component by replace the hash if it's not the same tone than the torso.

if there is a way to fix the broken characters
if you can make a video in how  you  go about fixing the wrong hashes and finding the right ones then we can try and get it fixed @cocomonksky

**Comment by KadDarem** [comment]
> > Note that in the images I shared it's not only the head that is wrong.
> 
> for me it was just the head that was reported and that changed  
> all we did was update the character script and then some heads color changed  to black from white 
> 
> > @DerHobbs @cocomonksky @RealStonerGamer can we get a video in how this is achieved ?
> 
> there is not really anything i can make a video on to recreate the issue 
> 
> > It should be possible to fix the wrong head component by replace the hash if it's not the same tone than the torso.
> 
> if there is a way to fix the broken characters
> if you can make a video in how  you  go about fixing the wrong hashes and finding the right ones then we can try and get it fixed @cocomonksky 
> 
> 
> 

You not need to do that by yourself. I will add a function to check and fix the head tone in the old character. 
I will do it after my holidays.

For the issue with new character created after the PR. I need to know how to reproduce the issue by getting the skin tone and head variation.

**Comment by DerHobbs** [comment]
New created!

{"shadows_opacity":0,"acne_visibility":0,"grime_opacity":1.0,"Body":-20262001,"LegsS":0.0,"ShouldersS":0.0,"MouthD":0.0,"foundation_palette_color_tertiary":0,"ChestS":0.0,"MouthCRD":0.0,"lipsticks_tx_id":0,"ChinH":0.0,"paintedmasks_visibility":0,"hair_visibility":1,"eyebrows_opacity":1.0,"grime_tx_id":1,"scars_visibility":1,"ArmsS":0.0,"paintedmasks_tx_id":0,"MouthCLW":0.0,"eyeliner_tx_id":0,"WaistW":0.0,"CheekBonesW":0.0,"JawD":0.0,"lipsticks_palette_id":0,"JawH":0.0,"blush_palette_id":0,"blush_palette_color_primary":0,"paintedmasks_palette_color_secondary":0,"freckles_visibility":0,"JawW":0.0,"beardstabble_color_primary":17129595,"blush_opacity":0,"Hair":2003861717,"hair_opacity":0,"CalvesS":0.0,"NeckW":0.0,"ageing_tx_id":20,"foundation_palette_color_secondary":0,"disc_opacity":0,"ageing_visibility":1,"lipsticks_visibility":0,"MouthCLH":0.0,"spots_visibility":1,"foundation_palette_id":0,"beardstabble_visibility":1,"ageing_opacity":1.0,"NoseDis":0.0,"Beard":1257638385,"complex_visibility":0,"sex":"mp_male","foundation_palette_color_primary":0,"ChinW":0.0,"shadows_palette_color_primary":0,"ShouldersM":0.0,"paintedmasks_palette_id":0,"MouthY":0.0,"eyeliner_visibility":0,"MouthX":0.0,"disc_visibility":0,"shadows_visibility":0,"eyebrows_tx_id":22,"HeadSize":0.0,"eyeliner_opacity":0,"NoseAng":0.0,"freckles_tx_id":0,"shadows_palette_color_tertiary":0,"paintedmasks_opacity":0,"CheekBonesD":0.0,"foundation_opacity":0,"complex_tx_id":0,"EarsW":0.0,"spots_opacity":1.0,"spots_tx_id":7,"moles_tx_id":0,"MouthW":0.0,"FaceD":0.0,"beardstabble_tx_id":1,"EarsA":0.0,"EyeAng":0.0,"MouthCRW":0.0,"foundation_tx_id":0,"NoseS":0.0,"scars_tx_id":14,"Torso":2966572863,"EarsD":0.0,"EyeBrowD":0.0,"NoseC":0.0,"albedo":0,"EyeLidW":0.0,"EyeD":0.0,"shadows_tx_id":0,"ShouldersT":0.0,"EyeBrowW":0.0,"Waist":1960266524,"hair_tx_id":0,"ULiphH":0.0,"MouthCLD":0.0,"EyeLidH":0.0,"Scale":1.05,"eyebrows_visibility":1,"beardstabble_opacity":1.0,"lipsticks_palette_color_secondary":0,"disc_tx_id":0,"complex_opacity":0,"EyeH":0.0,"grime_visibility":1,"acne_tx_id":0,"EyeDis":0.0,"Eyes":612262189,"Legs":1207869376,"freckles_opacity":0,"EyeBrowH":0.0,"shadows_palette_color_secondary":0,"paintedmasks_palette_color_primary":0,"EarsH":0.0,"MouthCRH":0.0,"moles_visibility":0,"LegsType":1389117221,"NoseH":0.0,"NeckD":0.0,"FaceS":0.0,"lipsticks_palette_color_primary":0,"blush_tx_id":0,"lipsticks_opacity":0,"paintedmasks_palette_color_tertiary":0,"shadows_palette_id":0,"ULiphD":0.0,"ULiphW":0.0,"eyebrows_color":1064202495,"EyeLidR":0.0,"LLiphD":0.0,"HeadType":1389122716,"FaceW":0.0,"scars_opacity":1.0,"EyeLidL":0.0,"moles_opacity":0,"hair_color_primary":0,"MouthCRLD":0.0,"LLiphW":0.0,"CheekBonesH":0.0,"eyeliner_color_primary":0,"foundation_visibility":0,"MouthCLLD":0.0,"blush_visibility":0,"acne_opacity":0,"eyeliner_palette_id":0,"ChinD":0.0,"BodyType":3447687317,"LLiphH":0.0,"HipsS":0.0,"NoseW":0.0,"lipsticks_palette_color_tertiary":0}
![2char](https://github.com/VORPCORE/vorp_character-lua/assets/101003021/4dacbfb2-2ab0-400e-94f6-fda3c109e649)

**Comment by outsider31000** [comment]
Yes but what options did you guys use to make this character? if you can list them here or make a small video. so that he can follow the same steps to find the issue.

Either way @KadDarem  if you do not have time at the moment I can revert it, you can make a pull request again when you are back from holidays no need to rush and go enjoy your holidays. 

It's just to stop people complaining about the issue.

**Comment by outsider31000** [comment]
But either way yall can use the latest release or premade, there it works.
also does it look like this when you making your characters or when you do /rc ? @RealStonerGamer  @DerHobbs  @cocomonksky

**Comment by outsider31000** [comment]
it has been reverted for now, once the issue the is found make a pull rquest again.
please see if the issue resolves with the new commit @DerHobbs @cocomonksky @RealStonerGamer
