### ISSUE TITLE
Face color character selection

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_character-lua#29]
This is how the character looks in the character selection, that's wrong
![image1](https://github.com/VORPCORE/vorp_character-lua/assets/101003021/08691e76-0951-4470-b3a3-8cce29c4c650)

When the character is spawned, it looks correct, maybe you can do something about it.
![image2](https://github.com/VORPCORE/vorp_character-lua/assets/101003021/08602ee2-f76a-485b-a3f8-524e697d4cf0)

**Comment by DerHobbs** [comment]
Another addition, the whole thing occurs with several characters that they look different in the character selection and after spawning.

**Comment by outsider31000** [comment]
npcs arent players, most changes wont show on npcs, character selector is based on npcs this is why i didnt add overlays cause they dont get applied to npcs

**Comment by outsider31000** [comment]
still facing this issue @DerHobbs

**Comment by DerHobbs** [comment]
Done
