### ISSUE TITLE
removeElementByValue error

### ISSUE THREAD

**Issue by Manliketjb** [VORPCORE/vorp_character-lua#31]
When pressing Enter to select your character a error shows 
![image](https://github.com/VORPCORE/vorp_character-lua/assets/82594996/7875e62f-39cc-438a-991d-5f0d066e4990)

New recipe deployment. no modifications have been made

**Comment by outsider31000** [comment]
remove menuapi and add vorp_menu ensure it where menuapi was

**Comment by Manliketjb** [comment]
> remove menuapi and add vorp_menu ensure it where menuapi was

yep that worked, Cheers
