### ISSUE TITLE
Hair accessory

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_character-lua#33]
The hair accessory isn't loading when logging in. If I use /rc, the hair accessory appears for a second and then disappears again. I've tried it with vorp_character without any modifications and with a new character, but it's always the same problem.
Regards.

When selecting the character, the hair accessory is there, then as seen in the video.

https://streamable.com/bepsyv

**Comment by outsider31000** [comment]
still happening ?

**Comment by vaggos-thanos** [comment]
yea it seems that it doesn't save the player's skin to the DB
also, I can not find in the vorp_chararcter this event `vorpcharacter:setPlayerSkinChange`

**Comment by outsider31000** [comment]
@DerHobbs

**Comment by DerHobbs** [comment]
Done

**Comment by outsider31000** [comment]
> Done

its working ?

**Comment by DerHobbs** [comment]
yes
