### ISSUE TITLE
Characters are half white and half black

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/vorp_character-lua#34]
Can you do anything about it? I have several players that this has happened to, it's a bit annoying :)
Is it supposed to be the case that this can happen?
![image](https://github.com/VORPCORE/vorp_character-lua/assets/39269181/1dcf5000-5aba-4714-8a73-db05a3f01ec1)
![bug_bild_2](https://github.com/VORPCORE/vorp_character-lua/assets/39269181/5b4022ab-bd61-4e7f-8a41-d9f31f6546fb)

**Comment by outsider31000** [comment]
make a video on how does that happen i need to see to be able to test and fix if theres an issue ofc

**Comment by outsider31000** [comment]
didnt got a response closing this
