### ISSUE TITLE
Deleting Character

### ISSUE THREAD

**Issue by JustRoys** [VORPCORE/vorp_character-lua#36]
When you press delete in the menu and press spawn the text will stay and if you accept while playing you delete your character. For some server that use outsider_needs the text is behind the UI

**Comment by outsider31000** [comment]
This isnt an issue with character script

**Comment by JustRoys** [comment]
it is because if you press delete and after that spawn the delete option still exist

**Comment by outsider31000** [comment]
i dont understand if you delete how do you still spawn ? if you delete the notify deletes too

**Comment by outsider31000** [comment]
or make a video so i can understand what you saying
