### ISSUE TITLE
update releases

### ISSUE THREAD

**Issue by rawb0t** [VORPCORE/vorp_character-lua#42]
apparently 1.4 is available but there's no release handy for 1.4, only 1.3

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_character-lua/assets/87246847/80c849c0-d0eb-4814-b66e-42160ca6edc1)

**Comment by rawb0t** [comment]
yes but some of us prefer to stick with the named, *usually-stable* releases instead of running potentially less-tested code. thank you for setting up the release
