### ISSUE TITLE
character/inventory issue loading

### ISSUE THREAD

**Issue by GothicRoze** [VORPCORE/vorp_character-lua#51]
![error pic](https://github.com/VORPCORE/vorp_character-lua/assets/53986686/c07bd2e6-5738-459b-9d33-f0a8ea22f93f)

I am getting this error when i try to launch my server with vorp character enabled. I have been trying to figure out how to fix it most of the day on my own and have gotten no where. I am really hoping someone can help.

**Comment by outsider31000** [comment]
yes thats the issue.

**Comment by GothicRoze** [comment]
Yeah, the server file had them listed wrong. I feel dumb for not catching that myself! Now, to go find more errors.....
