### ISSUE TITLE
Error after update 

### ISSUE THREAD

**Issue by diogoratomas** [VORPCORE/vorp_character-lua#52]
Having issues creating or selecting characters
![image-3](https://github.com/VORPCORE/vorp_character-lua/assets/43974049/c9bc0672-64b9-4db0-8d30-daae1095ba05)
![image-2](https://github.com/VORPCORE/vorp_character-lua/assets/43974049/1bbf5714-64d0-4814-8196-3ecbc338a235)
![image-1](https://github.com/VORPCORE/vorp_character-lua/assets/43974049/2558cf7e-ca13-4270-b93f-02eac202bf8d)
This error is showing on RedM console.

**Comment by JustRoys** [comment]
This issue has been fixed. It has nothing to do with the script. He didnt had vorp_menu ensured before vorp_core
