### ISSUE TITLE
Feature Request: Variants should be supported for lipsticks, eyeliners, and shadows

### ISSUE THREAD

**Issue by JulianLegler** [VORPCORE/vorp_character-lua#6]
Lipsticks, Eyeliners and Shadows come with the optional parameter "var" which enables the player to choose between different variations / styles of the forementioned makeup categories. 
E.g:
**Eyeliner var 15:**
![image](https://user-images.githubusercontent.com/10331752/235358408-c0bc0276-3dd9-4518-b43a-faae1103fedb.png)

**Eyeliner var 1 (only possible currently):**
![image](https://user-images.githubusercontent.com/10331752/235358484-2161bf21-fb0b-4581-ae6f-ca0ce9100c48.png)

They are not available in the character creator, but even more important, they are not loaded during `LoadPlayerComponents`. So even when using third-party scripts, which may uses the `skinPlayer` attribute, they will not be able to apply their makeup correctly without unnecessary overhead by manually applying it themselves. 
 
https://github.com/VORPCORE/vorp_character-lua/blob/10318157b637a4421e5f51f290019576f2be3954/client/client.lua#L467

Also, I think there are more color variations that are not supported. But I have to keep looking deeper into that.

**Comment by outsider31000** [comment]
it has been added
