### ISSUE TITLE
Can't remove component and switching cloths has a weird bug

### ISSUE THREAD

**Issue by KingKinay** [VORPCORE/vorp_character-lua#67]
Greetings. While creating your character with the newest version of vorp_character (vorp_menu and vorp_core updated 1 hour ago, and vorp_menu ensured before vorp_core) there's a bug with the belt option.

When I start at 0 and move right to 1, attempting to go back left to 0 instantly switches to the very last item. This doesn't affect the clothing at all.

On boots for example it's like this: 
Starting at 0 and moving right turns to 1.
On 1, moving left doesn't go back to 0 but jumps to 72.
While on 72, moving right doesn't bring it back to 0, it stays at 72.
On 72, moving left turns to 71, and moving right turns to 0 instead of 72.

I also can't remove components at all.
F8 doesn't show anything after pressing "REMOVE COMPONENT"
![Bild_2024-01-27_140315002](https://github.com/VORPCORE/vorp_character-lua/assets/92164796/66809f3c-d284-40ab-8182-f3dac027eced)

**Comment by JustRoys** [comment]
Having the same issue, can go back to 0 and cant remove component

**Comment by outsider31000** [comment]
move foward and back again this didnt exist  if you rather this removed and have to scroll 200 items seems better to keep it

**Comment by KingKinay** [comment]
Oh maybe I explained it poorly, I'm sorry. It just seemed like a bug. Didn't know it was intended to skip over 72 and 0. But that "remove component" isn't working is a bug, right?

**Comment by JustRoys** [comment]
> move foward and back again this didnt exist if you rather this removed and have to scroll 200 items seems better to keep it

In the vorp_clothingstore there was 0 to get rid of the clothing item. Right now its not possible to go to 0 to remove the clothingpeace.

**Comment by outsider31000** [comment]
Should be fixed this
