### ISSUE TITLE
Body 

### ISSUE THREAD

**Issue by JustRoys** [VORPCORE/vorp_character-lua#69]
My character was as thick like this (left character)
![image](https://github.com/VORPCORE/vorp_character-lua/assets/59421443/1afe5b90-7b98-4ae0-8489-e91dc64d3e7f)

Now its 
![image](https://github.com/VORPCORE/vorp_character-lua/assets/59421443/6cb14340-b4c5-48a4-b584-9adcebd98ec4)

I cant go as thick as before..

**Comment by outsider31000** [comment]
this was fixed
