### ISSUE TITLE
Error with no outfits saved

### ISSUE THREAD

**Issue by JustRoys** [VORPCORE/vorp_character-lua#73]
When you open the outfits menu in the clothing stores the menu crashes and a error appears. Your stuck in the clothingstore. Relogging will result in being stuck in the closed shops
![image](https://github.com/VORPCORE/vorp_character-lua/assets/59421443/68ad313f-d463-4b4e-ac98-27336aa87687)

**Comment by outsider31000** [comment]
can you try with new update
