### ISSUE TITLE
Rol currency

### ISSUE THREAD

**Issue by JustRoys** [VORPCORE/vorp_character-lua#80]
![image](https://github.com/VORPCORE/vorp_character-lua/assets/59421443/8350a14b-e3ff-4533-a790-41d13aae75c7)

Rol currency is not correct. 
ConfigShops.SecondChancePrice = 1, but still cant open the shop even if you have 1 rol.

**Comment by RealStonerGamer** [comment]
it was working for me yesterday

**Comment by JustRoys** [comment]
for me earlier to but tried it now and it isnt

**Comment by RealStonerGamer** [comment]
> for me earlier to but tried it now and it isnt

it just worked for me 
![image](https://github.com/VORPCORE/vorp_character-lua/assets/26008458/1271ffef-fdc5-4b35-bd43-5d8da951b7b0)
![image](https://github.com/VORPCORE/vorp_character-lua/assets/26008458/59771e85-a99e-4715-8bf1-d79bbcdc43c7)

**Comment by JustRoys** [comment]
Very strange. Will replace the server again.

**Comment by JustRoys** [comment]
its working and getting removed however the rol is still shown in the inventory as 1 so thats the issue

**Comment by RealStonerGamer** [comment]
> its working and getting removed however the rol is still shown in the inventory as 1 so thats the issue

its just not updating when you use your last one
its not removing  the last used 1 to 0  but your db shows  rol 0 so don"t have any to use but the inv writhing is not updated

**Comment by outsider31000** [comment]
If its an issue with inventory post in inventory.
