### ISSUE TITLE
Colour pallates didnt match after we bought the clothes

### ISSUE THREAD

**Issue by cocomonksky** [VORPCORE/vorp_character-lua#84]
i need some help about the pallates, when i change pallates in clothes its give me different colour after its done
the colour i choose was red but then it turn to different one

https://github.com/VORPCORE/vorp_character-lua/assets/134140565/09c95e35-f3f0-49db-99c0-910aba83e631

**Comment by outsider31000** [comment]
@KadDarem 
seems to be an issue with the Cache , if after relog it applies but not after leaving shop

**Comment by outsider31000** [comment]
@cocomonksky  you still have this?
