### ISSUE TITLE
Colour Tints issues

### ISSUE THREAD

**Issue by BaskinB** [VORPCORE/vorp_character-lua#87]
When testing the custom tints I was able to get them to apply however when rolling up my sleeves, or taking off my vest or opening the collar, the colors would reset and sometimes the shirt would clip through the vest, I tested it with the vorp clothing commands as well as kd_clotheswheel.

[Example](https://streamable.com/6bd3l0)

**Comment by outsider31000** [comment]
can you test this again ? seems to be fixed using vorp commands.

**Comment by outsider31000** [comment]
no answer will be closing this issue.
