### ISSUE TITLE
Custom clothing tints do not appear correctly

### ISSUE THREAD

**Issue by R1Productions** [VORPCORE/vorp_character-lua#92]
When I change the custom clothing tints, the color does not always appear correctly. I don't have any errors client and server side.

The coat with the chosen parameters
![NoPb](https://github.com/VORPCORE/vorp_character-lua/assets/154990697/f9e9aaba-5f41-4bf3-83b4-a62cb8cc3a16)
The problem I frequently encounter
![Pb](https://github.com/VORPCORE/vorp_character-lua/assets/154990697/e6636846-f375-4724-8962-a5fd02c8bf74)

**Comment by outsider31000** [comment]
Is this only for character selector? can you test with new updates and update here?

**Comment by R1Productions** [comment]
> Is this only for character selector? can you test with new updates and update here?

With new updates, this problem continue only with the Gloves. And it's not only for character selector.

**Comment by outsider31000** [comment]
I havent seen anyone reporting this issue does it still persist ? feel free to reopen  if yes.
