### ISSUE TITLE
Shoptypes "hair" or "makeup" does not read the pocket correct

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_character-lua#99]
1:
When I create a shoptype "hair" or "makeup" it does nor read the correct amount of cash in my pocket. (see pics)
![grafik](https://github.com/VORPCORE/vorp_character-lua/assets/48722973/86d4f803-0668-4271-b0e6-ca3d5a10c216)
![grafik](https://github.com/VORPCORE/vorp_character-lua/assets/48722973/39680c32-ae23-4230-b4b7-276f0caedfe7)
This charakter uses the shops after character creation (without logout)
2:
After logout and login again, it shows the right amount (only for the first time I use the shop). 
3:
After I go into the shop for the secound time and change something but buy nothing and go to "Close" it changes the makeup or hair without paying anything.
4:
Missing the option to create a shop "lifestyle" to change moles, spots, acne, etc.

**Comment by outsider31000** [comment]
update vorp core for the money fix.
